version: 0.2

env:
  variables:
    WAMBDA_DEBUG: "true"
    WAMBDA_USE_MOCK: "false"
    WAMBDA_NO_AUTH: "false"
    WAMBDA_DENY_SIGNUP: "false"
    WAMBDA_DENY_LOGIN: "false"
    WAMBDA_LOG_LEVEL: "INFO"
    DYNAMODB_TABLE: "table-wambda-csr001-main"

phases:
  install:
    runtime-versions:
      python: 3.13
  build:
    commands:
      - echo "Building and deploying Backend..."
      - sam build
      - sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --parameter-overrides ParameterKey=DEBUG,ParameterValue=$WAMBDA_DEBUG ParameterKey=UseMock,ParameterValue=$WAMBDA_USE_MOCK ParameterKey=NoAuth,ParameterValue=$WAMBDA_NO_AUTH ParameterKey=DenySignup,ParameterValue=$WAMBDA_DENY_SIGNUP ParameterKey=DenyLogin,ParameterValue=$WAMBDA_DENY_LOGIN ParameterKey=LogLevel,ParameterValue=$WAMBDA_LOG_LEVEL ParameterKey=DynamoDBTable,ParameterValue=$DYNAMODB_TABLE
